### ISSUE TITLE
Is the project up to date and working with the latest mumble and is there any where I can see it working?

### ISSUE THREAD

**Issue by victoriousgaming** [Rantanen/mumble-web#5]
Hi

I am interested in your project and wanted to ask a few questions regarding it.

1) Is the project up to date and working with the latest version of mumble 
2) Is there any where I can see it working as a demo?

Thank you very much.

Will Ferrer

**Comment by Rantanen** [comment]
Unfortunately not.

From the readme:

1) peerconnection library is prolly completely broken by now thanks to Google's changes to their libraries
2) UI does not exist.

There is nothing to see (there's some web endpoints that stream audio, etc.) and even those are painful to set up given you need to spend an hour figuring out how to compile old versions of Google's WebRTC libraries.

I've been long pondering whether I should just remove the project off GitHub given the current status is very broken.

**Comment by notthetup** [comment]
Please don't remove it from GitHub. You can add an 'unmaintained' badge http://unmaintained.tech/

But it would be super handy for someone if they want to implement something similar in the future when a bunch of this stuff (WebRTC) has settled down.

**Comment by victoriousgaming** [comment]
Hi Mikko

Thank you very much for the update, that helps with our decisions quite a
bit.

All the best.

Will Ferrer

**Comment by Rantanen** [comment]
@notthetup That's the reason why I haven't pulled it out. Thanks for pointing at the badge.

**Comment by notthetup** [comment]
Thank you!
